<a href="https://colab.research.google.com/github/chandrakanta-chaudhury/deep_learning-/blob/master/numba_python_cuda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#conda install numba cudatoolkit pyculib
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88


In [3]:
!pip3 install numba pyculib

     |████████████████████████████████| 92kB 27.3MB/s 
  Created wheel for pyculib: filename=pyculib-1.0.1-cp36-none-any.whl size=65705 sha256=a0c0066d9d9ec041dc26154842e26fe5b3f11cd21dcfa783cb3ab5a4adc1d697
  Stored in directory: /root/.cache/pip/wheels/c7/9b/0c/8ddc0966618312a4acbd2d8922c84892b413ce284f78a1c874
Successfully built pyculib


In [14]:
!apt-get install nvidia-cuda-toolkit

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libaccinj64-9.1 libcublas9.1 libcudart9.1 libcufft9.1 libcufftw9.1
  libcuinj64-9.1 libcurand9.1 libcusolver9.1 libcusparse9.1 libgail-common
  libgail18 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libnppc9.1 libnppial9.1
  libnppicc9.1 libnppicom9.1 libnppidei9.1 libnppif9.1 libnppig9.1 libnppim9.1
  libnppist9.1 libnppisu9.1 libnppitc9.1 libnpps9.1 libnvblas9.1 libnvgraph9.1
  libnvrtc9.1 libnvtoolsext1 libnvvm3 libthrust-dev libvdpau-dev
  nvidia-cuda-dev nvidia-cuda-doc nvidia-cuda-gdb nvidia-opencl-dev
  nvidia-profiler nvidia-visual-profiler ocl-icd-opencl-dev opencl-c-headers
  openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  gvfs libvdpau-doc libcupti-dev nvidia-driver libpoclu-dev openjdk-8-demo
  openjdk-8-source icedtea-8-plugin libnss-mdns fonts-ipafont-gothic
  fonts-ipafont-mincho fonts-wqy-m

In [0]:
from numba import vectorize

In [0]:
@vectorize(['float32(float32, float32)'], target='cuda')
def Add(a, b):
  return a + b

In [35]:
N = 100000
A = np.ones(N, dtype=np.float32)
B = np.ones(A.shape, dtype=A.dtype)
C = np.empty_like(A, dtype=A.dtype)
C = Add(A, B)


NvvmSupportError: ignored

In [36]:
!apt-get install nvidia-cuda-toolkit
!pip3 install numba

import os
os.environ['NUMBAPRO_LIBDEVICE'] = "/usr/lib/nvidia-cuda-toolkit/libdevice"
os.environ['NUMBAPRO_NVVM'] = "/usr/lib/x86_64-linux-gnu/libnvvm.so"

from numba import cuda
import numpy as np
import time

Reading package lists... Done
Building dependency tree       
Reading state information... Done
nvidia-cuda-toolkit is already the newest version (9.1.85-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.


In [0]:
 @cuda.jit
def hello(data):
    data[cuda.blockIdx.x, cuda.threadIdx.x] = cuda.blockIdx.x

numBlocks = 5
threadsPerBlock = 10

data = np.ones((numBlocks, threadsPerBlock), dtype=np.uint8)


In [38]:
hello[numBlocks, threadsPerBlock](data)

print(data)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]]


In [0]:
from numba import vectorize

In [0]:
@vectorize(['float32(float32, float32)'], target='cuda')
def Add(a, b):
  return a + b

N = 100000
A = np.ones(N, dtype=np.float32)
B = np.ones(A.shape, dtype=A.dtype)
C = np.empty_like(A, dtype=A.dtype)
C = Add(A, B)

In [41]:
print(C)

[2. 2. 2. ... 2. 2. 2.]
